import Head from 'next/head';
const Header = () => {
  return (
    <Head>
      <title>Pokedex</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/assets/pokeball--v2.png" />
    </Head>
  );
};
export default Header;
