import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.scss';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Pokedex powered by Next.js!</h1>

        <p className={styles.description}>
          <Link href="/pokemon">
            Get started by navigating
            <code className={styles.code}>pokemon listing !!!</code>
          </Link>
        </p>

        <div className={styles.grid}></div>
      </main>
    </div>
  );
}
